### ISSUE TITLE
add link to go docs

### ISSUE THREAD

**Issue by carlsverre** [singlestore-labs/singlestore-go#1]
https://pkg.go.dev/github.com/singlestore-labs/singlestore-go/management

and make sure it's updated whenever the version changes - not sure how to do that.

**Comment by carlsverre** [comment]
I believe you can update by making a request to the proxy api: https://proxy.golang.org/github.com/singlestore-labs/singlestore-go/management/@v/v0.1.1.info at a specific version number

https://pkg.go.dev/about#adding-a-package

**Comment by noprysk-ua** [comment]
`curl https://proxy.golang.org/github.com/singlestore-labs/singlestore-go/management/@v/v0.1.1.info` where `v0.1.1` is the latest version indeed published the indicated version (I've tested in a separate repo). Preparing a commit...

**Comment by noprysk-ua** [comment]
Updated the `.update` script to publish new versions and added a link to the docs to `README.md` https://github.com/singlestore-labs/singlestore-go/commit/56e42d47929b52ccf2a4d5e29dba8aa63153789d.
